vich_uploader:
    db_driver: orm

    mappings:
        cars:
            uri_prefix: /images/vente/cars
            upload_destination: '%kernel.project_dir%/public/images/vente/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        prestations:
            uri_prefix: /images/prestations
            upload_destination: '%kernel.project_dir%/public/images/prestations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
